### ISSUE TITLE
npm run start failed

### ISSUE THREAD

**Issue by SvenAugustus** [WizTeam/WizNoteLite#27]
when i start, i got failed. Could someone help for this issue ?  

```
node -v
```
v14.5.0

```shell
npm run start
```

```
> nf start -p 3000

sh: nf：未找到命令
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! wiznotelite@1.1.0 start: `nf start -p 3000`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the wiznotelite@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/nodejs/npm/cache/_logs/2020-07-18T04_15_45_662Z-debug.log

```
```shell
cat /var/lib/nodejs/npm/cache/_logs/2020-07-18T04_15_45_662Z-debug.log
```
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v14.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wiznotelite@1.1.0~prestart: wiznotelite@1.1.0
6 info lifecycle wiznotelite@1.1.0~start: wiznotelite@1.1.0
7 verbose lifecycle wiznotelite@1.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle wiznotelite@1.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/svenaugustus/archp/src/WizNoteLite/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle wiznotelite@1.1.0~start: CWD: /home/svenaugustus/archp/src/WizNoteLite
10 silly lifecycle wiznotelite@1.1.0~start: Args: [ '-c', 'nf start -p 3000' ]
11 info lifecycle wiznotelite@1.1.0~start: Failed to exec start script
12 verbose stack Error: wiznotelite@1.1.0 start: `nf start -p 3000`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1051:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
12 verbose stack     at Process.callbackTrampoline (internal/async_hooks.js:123:14)
13 verbose pkgid wiznotelite@1.1.0
14 verbose cwd /home/svenaugustus/archp/src/WizNoteLite
15 verbose Linux 5.7.8-arch1-1
16 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
17 verbose node v14.5.0
18 verbose npm  v6.14.6
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error wiznotelite@1.1.0 start: `nf start -p 3000`
23 error spawn ENOENT
24 error Failed at the wiznotelite@1.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by wizweishijun** [comment]
npm install -g foreman

**Comment by SvenAugustus** [comment]
@wizweishijun it works ! Thanks for help. it maybe good to add this in README.md
